### ISSUE TITLE
[Task 3] Fix the response codes for wrong input for POST /users/{user_id}/tasks

### ISSUE THREAD

**Issue by Pabriones** [North-Seattle-College/ad440-winter2021-tuesday-repo#212]
|Task 3| Fix the response codes for wrong input for POST /users/{user_id}/task and document the required input and expected output (Swagger in folder /swagger in the project – filename swagger-users.yaml)

**Comment by toddysm** [comment]
POST should return response code 405
PUT with wrong input (input is in few places - URL has the ID and the body has the JSON) should return response code 400
PUT with wrong integer ID should return 404
DELETE with wrong integer ID should return 404
DELETE with non-integer ID should return 400

For the Swagger - create a folder /swagger and save the yml/json in a filename swagger-users-userid.***

**Comment by Pabriones** [comment]
> POST should return response code 405
> PUT with wrong input (input is in few places - URL has the ID and the body has the JSON) should return response code 400
> PUT with wrong integer ID should return 404
> DELETE with wrong integer ID should return 404
> DELETE with non-integer ID should return 400

I just realized that my task is actually **POST /users/{user_id}/tasks** and not  _POST /users/{user_id}_

**Comment by Pabriones** [comment]
Date | Activity | Time Spent
-- | -- | --
2/23/2021 | Test file out to see what errors is being generated | 2 hours
2/24/2021 | Research as to why even after all changes were made same wrong error keeps popping up | 3 hours
02/28/2021 | Keep testing and updating code | 4 hours
03/01 - 03/05/2021 |  Keep testing and updating code and create yaml file for swagger documentation | 5 hours

**Comment by Pabriones** [comment]
**Instruction to test **POST /users/{user_id}/tasks**:**

- Login to [Azure portal ](https://portal.azure.com/#home)
- Go to [Resource Groups](https://portal.azure.com/#blade/HubsExtension/BrowseResourceGroups)
- Then select nsc-rg-dev-usw2-tuesday
- Under Overview, select nsc-func-dev-usw2-tuesday [Function APP]
- Under toolbar on the left hand side, select _**Functions**_ under Functions
- Then select [HttpTriggerUserIdTask](https://portal.azure.com/#blade/WebsitesExtension/FunctionMenuBlade/functionOverview/resourceId/%2Fsubscriptions%2F9f4dcf43-aa06-457b-b975-f0216baef20d%2FresourceGroups%2Fnsc-rg-dev-usw2-tuesday%2Fproviders%2FMicrosoft.Web%2Fsites%2Fnsc-func-dev-usw2-tuesday%2Ffunctions%2FHttpTriggerUserIdTask)
- Then select Code + Test on the left hand side toolbar
- Select Test/Run, 
- Begin Testing
