### ISSUE TITLE
GitHub action for headless chrome testing for UI endpoint users/id/tasks

### ISSUE THREAD

**Issue by All-Schuck-Up** [North-Seattle-College/ad440-winter2021-tuesday-repo#213]
Write action to run the headless chrome UI test for /user/{userId}/tasks endpoint.

**Comment by All-Schuck-Up** [comment]
DATE | ACTIVITY | TIME
-- | -- | --
02/20 | Research on headless chrome and automation | 2 hours
02/20 | Wrote simple script using 'puppeteer' for UI testing in headless chrome | 1 hour

Puppeteer documentation: 
- https://developers.google.com/web/tools/puppeteer/get-started

Simple script to launch headless browser, navigate to desired page and capture screenshot.
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('<url goes here>');
    await page.screenshot({ path: '<name of output file goes here>' })
})
```

**Comment by All-Schuck-Up** [comment]
@toddysm Where should I place this script in the folder structure?

**Comment by toddysm** [comment]
The deliverable is a GitHub action that performs the task and saves the screenshot in Azure Storage container.
Naming conventions:
- GitHub Action: Headless Chrome /users/id/tasks
- Storage Account: nscstrdevusw2tuecommon
- Container: screenshots
- Filename Pattern: capture-users-id-tasks-YYYY-mm-DD-HH-MM-SS.png

**Comment by All-Schuck-Up** [comment]
github action used from the marketplace
https://github.com/marketplace/actions/screenshot-action
