### ISSUE TITLE
Write action to run the headless Chrome UI tests for /users/{user_id}

### ISSUE THREAD

**Issue by philckim** [North-Seattle-College/ad440-winter2021-tuesday-repo#214]
**Is your feature request related to a problem? Please describe.**
Required for ability perform UI tests for /users/{user_id} via headless Chrome

**Describe the solution you'd like**
GitHub action to run UI tests for /users/{user_id} in headless Chrome 

**Describe alternatives you've considered**
N/A - feature is required as-is to function with rest of team/class

**Comment by philckim** [comment]
Date | Activity | Time Spent
-- | -- | --
2/22/2021 | Research Headless Chrome & GitHub Actions testing | 180 minutes
2/22/2021 | Wrote simple script using 'puppeteer' for UI testing in headless chrome | 60 minutes
2/28/2021 | Worked on my Github action trying to get tests to pass | 120 minutes
3/1/2021 | Worked with group to troubleshoot the Github Actions | 120 minutes



**Puppeteer documentation:**
https://developers.google.com/web/tools/puppeteer/get-started
Simple script to launch headless browser, navigate to desired page and capture screenshot.

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('<url goes here>');
    await page.screenshot({ path: '<name of output file goes here>' })
})
```

**Comment by philckim** [comment]
**Steps taken to resolve this:**

1.  Research what headless Chrome is, how to run it, and GitHub Actions
2. ...

**Comment by philckim** [comment]
**To Run:**
- Navigate to Github Actions page under school's Github repo
- Click on the appropriate workflow
- Manually run the workflow

**Comment by toddysm** [comment]
The deliverable is a GitHub action that performs the task and saves the screenshot in Azure Storage container.
Naming conventions:
- GitHub Action: Headless Chrome /users/id
- Storage Account: nscstrdevusw2tuecommon
- Container: screenshots
- Filename Pattern: capture-users-id-YYYY-mm-DD-HH-MM-SS.png
