### ISSUE TITLE
Cannot Post data to sql db

### ISSUE THREAD

**Issue by YAG0731** [North-Seattle-College/ad440-winter2021-tuesday-repo#255]
**Describe the bug**
When I try to create a user, fail to do a post request because 500 internal server error

**To Reproduce**
1. Go to [web app](https://nscstrdevusw2tuecommon.z5.web.core.windows.net/)
2. Click on the 'Create a User' button
3. Enter the values as instructed, and then hit submit button
4. See an error

**Expected behavior**
When submit button is hit, data will successfully be sent to DB and a new user will be created. An alert message will pop up and show 'Your registration was successfully submitted!'

**Screenshots**

- error message

![image](https://user-images.githubusercontent.com/57081128/109732607-5192de80-7b72-11eb-9089-d394275be9cd.png)

- Testing user function on Azure received the following error

`Result: Failure Exception: IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'joinDate', table 'nsc-sqldb-dev-usw2-toddysm.dbo.users'; column does not allow nulls. INSERT fails. (515) `

- Current users table 

![image](https://user-images.githubusercontent.com/57081128/109731780-c49b5580-7b70-11eb-9026-bcadd4ce69ca.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [10.0]

**Additional context**

**Comment by All-Schuck-Up** [comment]
## To test /api/users POST route:
(I suggest postman to simplify testing the api)
These instruction will go into how to test via postman
1. open postman

![postman-ist1](https://user-images.githubusercontent.com/55608123/109885518-79964680-7c33-11eb-96c9-d5e4c9972976.png)

2. Select headers tab and fill in the fields according to img below.

![postman2](https://user-images.githubusercontent.com/55608123/109885649-bc581e80-7c33-11eb-9452-b49071ac9920.png)

3.  Select body tab and fill according to img below.

![postman3](https://user-images.githubusercontent.com/55608123/109885791-fde8c980-7c33-11eb-8d06-8bcd32b4cd71.png)

```
{
    "firstName": "<input goes here>",
    "lastName": "<input goes here>",
    "email": "<input goes here>",
    "userPassword": "<input goes here>"
}
```

4. Click send and you should get the created users id back in json format
