### ISSUE TITLE
[Task 3] Use Github actions to deploy changes to the React app to the storage resource

### ISSUE THREAD

**Issue by andylwilson** [North-Seattle-College/ad440-winter2021-tuesday-repo#75]
**Task Overview**

This task leverages Github Actions to automate the UI file upload process to an Azure Storage account when changes are pushed to the repo.

**Comment by jlsnow301** [comment]
Sorely needed, it's such a pain to move these files manually

**Comment by andylwilson** [comment]
## Implementation

This task uses a GitHub Action workflow to automate the process of uploading our static website deployment to the cloud with Azure Storage, initiated after changes are made and pushed to the repo. This implementation follows official Microsoft documentation Luca Andolina found [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions). This documentation also includes information on deploying to an Azure CDN, but for our purposes we will be assuming our deployment is for a simple static website that doesn't require those needs.

**Storage Account**

It is assumed that we have an Azure subscription and a Github repository for our website code. With that being the case, we first must sign in to the Azure portal and create a new storage account to host the website. From the portal home page, click on the Storage Accounts button, then click "New" and customize your storage account with name and resource group; in our case they will be `nsc-rg-dev-usw2-tuesday` for the resource group, and something descriptive that adheres to our naming convention for the account name.

Make sure to note the account name as we will need it later. You must also make sure to pick `StorageV2 (General Purpose v2)` as the "kind," as it is the only option that works for static websites.

- Now find your storage account and view the account overview.
- Click `static website` from the left hand navigation.
- Flip the switch from disabled to enabled, which will provide you with your static website's endpoint url, and let you set an index and error document path (we can just use index.html and 404.html).
- In the left hand navigation, find and select `Storage Explorer` (it might say "preview").
- Expand the `BLOB CONTAINERS` file structure, then click on `$web`. This is where your static website files will be initially uploaded, and then overwritten automatically after our Github Action comes into play. 
- Upload your website files here manually, and then go back to the static website endpoint we created to verify that your website is displaying.

**Github Action**

Finally, we will use the Github Actions script that is attached to this Issue to automate the updating of those website files in the storage account. The last thing we will need is an Azure Service Principal to handle our credentials within the script. You can either create one using the Azure CLI command found in the documentation above if you are using a personal Azure subscription, or if you are using an organization or school subscription, you can have your administrator or instructor create one for you.

Once you have the SP, you will need to either manually add it to your personal Github repo as a Github secret that the Github Action can reference to run the Azure automation, or have your administrator or instructor add it to your organization's repo and provide you the secret name.

If manually adding, input it into Github under `Settings > Secrets > New Repository Secret`, and give it a descriptive name. 

Once you have the name of the secret, make the following modifications to the Github Action script:
- The `creds` field must have the name of your service principal secret.
- Insert your storage account name in the `inlineScript` field.

Once these actions are completed, you can verify by pushing a new pull request, and then either checking from within the Actions tab on Github, checking the static website itself for changes if any were made, or by going into the Azure portal, finding your storage account, and clicking `Storage Explorer > BLOB CONTAINERS > $web` and verifying the files and their modified dates.

**Comment by andylwilson** [comment]
|Date|Activity|TimeSpent|
|-|-|-|
|1/22/2021|Researched Github Actions|2 hours|
|1/24/2021|Team Zoom Meeting|1 hour|
|1/25/2021|Read and followed documentation from Luca|2 hours|
|1/25/2021|Troubleshooting service principal creation, got help from Toddy|1 hours|
|2/09/2021|Wrote up task and activity documentation|1 hour|
